# Generated by Django 5.2.18 on 2026-10-07 20:13

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('committed', 'Committed')], default='previewed', max_length=20)),
                ('rows', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'import batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='OutreachRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.CharField(max_length=200)),
                ('visit_type', models.CharField(max_length=200)),
                ('last_visit', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='outreach.importbatch')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='outreach.patient')),
            ],
            options={
                'ordering': ['last_visit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OutreachAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('no_answer', 'No Answer'), ('voicemail', 'Voicemail'), ('scheduled', 'Scheduled'), ('not_interested', 'Not Interested')], max_length=20)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_actions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='outreach.outreachrecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('action_type', 'scheduled'), ('appointment_date__isnull', False)), models.Q(models.Q(('action_type', 'scheduled'), _negated=True), ('appointment_date__isnull', True)), _connector='OR'), name='appointment_date_required_only_for_scheduled')],
            },
        ),
        migrations.AddIndex(
            model_name='outreachrecord',
            index=models.Index(fields=['patient', 'status'], name='record_patient_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='outreachrecord',
            constraint=models.UniqueConstraint(models.F('patient'), django.db.models.functions.text.Lower('visit_type'), models.F('last_visit'), name='unique_record_per_patient_visit_type_last_visit'),
        ),
    ]
