# Generated by Django 5.2.18 on 2026-10-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
